{
 "title": "Cluster Cost & Utilization Overview Copy",
 "description": "A dashboard to help manage Kubernetes cluster costs and resources",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Discount", "query": "100" }
  ]
 },
 "panels": [
  { "title": "Cost Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Estimated Monthly Cluster Resource Costs",
   "type": "bargauge",
   "description": "Monthly estimated costs according to latest 1 hour resource usage, Note, if you use virtual kubelet or EKS Pod, we do not compute the virtual node costs.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    avg(\n        avg_over_time(node_total_hourly_cost[1h])\n        * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n    )\n     \nby (node)) * 730 * ($Discount/100.0)"
    },
    {
     "expr": "sum(\n  sum(\n    sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}) by (container, pod, node, namespace) \n    * on (node) group_left() \n    avg(\n      avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n    ) by (node)\n    \n)\n\n+\n\nsum(\n  sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"} / 1024./ 1024. / 1024.) by (container, pod, node, namespace) \n  * on (node) group_left() \n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n  ) by (node) \n  \n)\n) * 730 * ($Discount/100.0)"
    },
    {
     "expr": "sum (\n  sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node) \n  ) by (node)\n\n+\n\n  sum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * 730 * ($Discount/100.)"
    },
    {
     "expr": "sum(\n  sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n      avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n      ) by (node)\n  ) by (node)\n) * 730 * ($Discount/100.)"
    },
    {
     "expr": "sum(\n  sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"} / 1024./ 1024. / 1024.) by (container, pod, node, namespace) * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * 730 * ($Discount/100.)"
    },
    {
     "expr": "sum(\n  sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(\n    avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * 730 * ($Discount/100.)"
    },
    {
     "expr": "sum(\n  sum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n    avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * 730 * ($Discount/100.)"
    }
   ]
  },
  {
   "title": "Node Resource Cost & Utilization",
   "type": "table",
   "description": "This table shows the comparison of application CPU usage vs the capacity of the node (measured over last 60 minutes)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"} \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node) \n\n/\n\nsum(\n  kube_node_status_capacity{resource=\"cpu\", unit=\"core\"} \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node) \n\n* 100"
    },
    {
     "expr": "sum(\n  label_replace(irate(container_cpu_usage_seconds_total{container!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(^[^:]+)\") \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node)\n/\nsum(\n  kube_node_status_capacity{resource=\"cpu\", unit=\"core\"} \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n) by (node) \n\n* 100"
    },
    {
     "expr": "avg(\n  avg_over_time(node_cpu_hourly_cost[1h]) \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node)  * ($Discount/100.)"
    },
    {
     "expr": "sum(\n\n  sum(\n    label_replace(irate(container_cpu_usage_seconds_total{container!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(^[^:]+)\")  \n     * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n  ) by (container, pod, node, namespace) \n\n  * on (node) group_left() \n \n  avg(\n    avg_over_time(node_cpu_hourly_cost[1h])  \n    * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n  ) by (node) \n\n) by (node)  * ($Discount/100.)"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"}  \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n) by (node) * 100\n\n/ \n\nsum(\n  kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}  \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node)"
    },
    {
     "expr": "sum(\n  label_replace(container_memory_usage_bytes{container!=\"\"}, \"node\", \"$1\", \"instance\",\"(^[^:]+)\")  \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node) * 100\n\n/\nsum(\n  kube_node_status_capacity{resource=\"memory\", unit=\"byte\"} \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node)"
    },
    {
     "expr": "avg(\n  avg_over_time(node_ram_hourly_cost[1h])) by (node) \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n) by (node)  * ($Discount/100.)"
    },
    {
     "expr": "sum(\n\n  sum(\n    label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(^[^:]+)\") \n    * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n  ) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 \n\n  * on (node) group_left()\n\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) \n    * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n  ) by (node)\n  \n) by (node)  * ($Discount/100.)\n"
    },
    {
     "expr": "avg(\n  avg_over_time(node_total_hourly_cost[1h])\n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n) by (node) * ($Discount/100.)"
    }
   ]
  },
  {
   "title": "Cluster Utilization Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "description": "Current CPU utilization from applications usage vs allocatable CPU",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"\"}[5m]), \"node\", \"$1\", \"instance\",  \"(^[^:]+)\")  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))\n\n/\n\nsum(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"} * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)) \n\n* 100"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "gauge",
   "description": "Current CPU reservation requests from applications vs allocatable CPU",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"} * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) ) \n/ \nsum(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"} * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) )\n* 100"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "gauge",
   "description": "Current RAM use vs RAM available",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_working_set_bytes{container!=\"\"}, \"node\", \"$1\", \"instance\",  \"(^[^:]+)\")  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))\n\n/\n\nsum(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"} * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) ) \n* 100"
    }
   ]
  },
  {
   "title": "RAM Requests",
   "type": "gauge",
   "description": "Current RAM requests vs RAM available",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) )\n /\n sum(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) )\n) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))",
     "legendFormat": "capacity"
    },
    {
     "expr": "SUM(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"\"}[5m]), \"node\", \"$1\", \"instance\",  \"(^[^:]+)\")  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Cluster Memory (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "SUM(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)  / 1024 / 1024 / 1024 )",
     "legendFormat": "capacity"
    },
    {
     "expr": "SUM(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"} * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)/ 1024 / 1024 / 1024)",
     "legendFormat": "requests"
    },
    {
     "expr": "SUM(label_replace(container_memory_working_set_bytes{id=\"/\"}, \"node\", \"$1\", \"instance\",  \"(^[^:]+)\")  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)) / 1024 / 1024 / 1024",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Node Utilization Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (label_replace(irate(container_cpu_usage_seconds_total{container!=\"\"}[5m]), \"node\", \"$1\", \"instance\",  \"(^[^:]+)\"))/sum by (node) (kube_node_status_capacity{resource=\"cpu\", unit=\"core\",node!~\"eklet\"})",
     "legendFormat": "cpu utilization"
    }
   ]
  },
  {
   "title": "Node Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (label_replace(container_memory_working_set_bytes{container!=\"\"}, \"node\", \"$1\", \"instance\",  \"(^[^:]+)\"))/sum by (node) (kube_node_status_capacity{resource=\"memory\", unit=\"byte\",node!~\"eklet\"})",
     "legendFormat": "cpu utilization"
    }
   ]
  }
 ]
}