{
 "title": "Workload Insight",
 "description": "Workload Insight",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "WorkloadType",
    "label": "WorkloadType",
    "query": {
     "query": "label_values(crane_analysis_resource_recommendation{namespace=~\"$Namespace\"},owner_kind)"
    }
   },
   {
    "name": "Workload",
    "label": "Workload",
    "query": {
     "query": "label_values(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"$WorkloadType\"},owner_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Workload Pods Insight - CPU",
   "type": "timeseries",
   "description": "Workload optimize model dashboard, calculate all pods metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"^$Workload-.*$\",container!=\"POD\",namespace=\"$Namespace\",container!=\"\"}[3m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"cpu\",owner_name=~\"$Workload\"}) *\ncount(kube_pod_info{namespace=\"$Namespace\",pod=~\"^$Workload-.*$\",})\n",
     "legendFormat": "recommend"
    }
   ]
  },
  {
   "title": "Workload Pods Insight - Memory",
   "type": "timeseries",
   "description": "Workload optimize model dashboard, calculate all pods metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"^$Workload-.*$\",namespace=\"$Namespace\",container!=\"\"})/1024/1024/1024",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$Namespace\",unit=\"byte\",resource=\"memory\",pod=~\"^$Workload-.*$\"})/1024/1024/1024",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"memory\",owner_name=\"$Workload\"}) *\ncount(kube_pod_info{namespace=\"$Namespace\",pod=~\"^$Workload-.*$\",}) /1024/1024/1024\n",
     "legendFormat": "recommend"
    }
   ]
  },
  {
   "title": "Workload Spec Insight - CPU",
   "type": "timeseries",
   "description": "Workload insight for CPU, Spec level",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod=~\"^$Workload-.*$\",container!=\"POD\",namespace=\"$Namespace\",container!=\"\"}[3m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"cpu\",owner_name=~\"$Workload\"})\n",
     "legendFormat": "recommend"
    }
   ]
  },
  {
   "title": "Workload Spec Insight - Memory(GB)",
   "type": "timeseries",
   "description": "Workload Insight, Spec level.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{pod=~\"^$Workload-.*$\",namespace=\"$Namespace\",container!=\"\"})/1024/1024/1024",
     "legendFormat": "usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$Namespace\",unit=\"byte\",resource=\"memory\",pod=~\"^$Workload-.*$\"})/1024/1024/1024",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"memory\",owner_name=~\"$Workload\"})\n/1024/1024/1024 ",
     "legendFormat": "recommend"
    }
   ]
  }
 ]
}