{
 "title": "Container  and Node Analysis V1",
 "description": "容器与节点推荐分析",
 "tags": [ "Kubehan" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "集群", "query": "prometheus" },
   {
    "name": "Host",
    "label": "主机名",
    "query": {
     "query": "label_values(node_uname_info{}, nodename)"
    }
   },
   {
    "name": "Node",
    "label": "节点",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job.*\",nodename=~\"$Host\"}, instance)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   { "name": "NameSpace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "WorkloadType",
    "label": "WorkloadType",
    "query": {
     "query": "label_values(crane_analysis_resource_recommendation{namespace=~\"$NameSpace\"},owner_kind)"
    }
   },
   {
    "name": "Workload",
    "label": "Workload",
    "query": {
     "query": "label_values(crane_analysis_resource_recommendation{namespace=~\"$NameSpace\",owner_kind=\"$WorkloadType\"},owner_name)"
    }
   },
   {
    "name": "Container",
    "label": "Container",
    "query": {
     "query": "label_values(crane_analysis_resource_recommendation{namespace=~\"$NameSpace\",owner_kind=\"$WorkloadType\",owner_name=~\"$Workload\"},container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values({namespace=~\"$NameSpace\",node=~\"$Node\",container=~\"$Container\"},pod)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "集群机器资源总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "集群机器资源利用率排行",
     "type": "timeseries",
     "description": "结果与free -m 命令接近\n\n(1 - (node_memory_MemAvailable_bytes / (node_memory_MemTotal_bytes)))",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$Node\"} / (node_memory_MemTotal_bytes{instance=~\"$Node\"}))) * 100",
       "legendFormat": "Memory Usage {{instance}}"
      },
      {
       "expr": "100 - (avg by(instance) (irate(node_cpu_seconds_total{instance=~\"$Node\",mode=\"idle\"}[2m])) * 100)",
       "legendFormat": "CPU Usage {{instance}}"
      }
     ]
    },
    {
     "title": "Cluster Memory Requests (%) ",
     "type": "timeseries",
     "description": "【已分配资源】",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",label_node_kubernetes_io_instance_type!~\"eklet\"}) / sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", label_node_kubernetes_io_instance_type!~\"eklet\"})",
       "legendFormat": "cluster memory request"
      },
      {
       "expr": "sum(crane_analysis_resource_recommendation{resource=\"memory\"})/sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", label_node_kubernetes_io_instance_type!~\"eklet\"})",
       "legendFormat": "recommendation memory request"
      }
     ]
    }
   ]
  },
  {
   "title": "集群资源浪费情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU 浪费率（申请/实际）展板排行榜",
     "type": "timeseries",
     "description": "值越大代表浪费的越多 【 request  >> usage 】\n值越小代表过度利用的越多【 request  << usage 】\n\n本着Request值与实际使用值越接近的原则，Request值使用不足95% 认为存在浪费的情况\n\n计算公式说明：\n1. (节点request - wss * 1.05)/节点request\n2. 计算值为负数则代表存在过度利用情况，实际使用大于实际申请\n3. 计算值为正数则代表存在浪费情况，实际申请request未充分利用，大于实际使用",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "(sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"^$Node$\"})by (node) - sum(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",node=~\"^$Node$\"}[2m])) by (node) * 1.05) / sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"^$Node$\"})by (node)",
       "legendFormat": "CPU资源浪费率  {{node}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\",node=~\"^$Node$\"})by (node)",
       "legendFormat": "已分配CPU资源 {{node}}"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container !=\"\",container!=\"POD\",node=~\"^$Node$\"}[2m])) by (node)",
       "legendFormat": "已使用CPU资源 {{node}}"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"cpu\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "CPU资源总量 {{node}}"
      }
     ]
    },
    {
     "title": "内存浪费率（申请/实际）展板排行榜",
     "type": "timeseries",
     "description": "值越大代表浪费的越多 【 request  >> usage 】\n值越小代表过度利用的越多【 request  << usage 】\n\n本着Request值与实际使用值越接近的原则，Request值使用不足95% 认为存在浪费的情况\n\n计算公式说明：\n1. (节点request - wss * 1.05)/节点request\n2. 计算值为负数则代表存在过度利用情况，实际使用大于实际申请\n3. 计算值为正数则代表存在浪费情况，实际申请request未充分利用，大于实际使用",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "(sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node) - sum (container_memory_working_set_bytes{container !=\"\",container!=\"POD\",node=~\"^$Node$\"})  by (node) * 1.05) / sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)",
       "legendFormat": "MEM资源浪费率  {{node}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node)",
       "legendFormat": "已分配MEM资源 {{node}}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container !=\"\",container!=\"POD\",node=~\"^$Node$\"}) by (node)",
       "legendFormat": "已使用MEM资源 {{node}}"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
       "legendFormat": "MEM资源总量 {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "资源推荐总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "资源推荐总览",
     "type": "table",
     "description": "资源推荐明细",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(crane_analysis_resource_recommendation{resource=\"memory\",namespace=~\"$NameSpace\",owner_kind=\"$WorkloadType\",owner_name=~\"$Workload\",container=~\"$Container\"}) by (owner_name,namespace,container)",
       "legendFormat": "内存推荐"
      },
      {
       "expr": "sum(crane_analysis_resource_recommendation{resource=\"cpu\",namespace=~\"$NameSpace\",owner_kind=\"$WorkloadType\",owner_name=~\"$Workload\",container=~\"$Container\"}) by (owner_name,namespace,container)",
       "legendFormat": "CPU推荐"
      },
      {
       "expr": "sum(crane_analysis_replicas_recommendation{namespace=~\"$NameSpace\",owner_kind=\"$WorkloadType\",owner_name=~\"$Workload\"})by(owner_name,owner_kind,namespace)",
       "legendFormat": "副本数推荐"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,namespace)",
       "legendFormat": "内存需求"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,namespace)",
       "legendFormat": "CPU需求"
      }
     ]
    }
   ]
  },
  {
   "title": "容器内存使用总览 $Container ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Container 内存使用量总览",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)",
       "legendFormat": "内存配置量 {{container}} {{pod}}"
      },
      {
       "expr": "sum(crane_analysis_resource_recommendation{resource=\"memory\",namespace=\"$NameSpace\",owner_kind=\"$WorkloadType\",owner_name=\"$Workload\",container=~\"$Container\"}) by (owner_name,container,namespace,resource)",
       "legendFormat": "内存推荐量 {{container}}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "实际使用量 {{container}}"
      }
     ]
    },
    {
     "title": "$Container 内存利用率总览",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container,pod) / sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod) ",
       "legendFormat": "实际使用/实际配置占比   {{container}} {{pod}}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) /sum(crane_analysis_resource_recommendation{resource=\"memory\",namespace=\"$NameSpace\",owner_kind=\"$WorkloadType\",owner_name=\"$Workload\",container=\"$Container\"}) by (container,pod)",
       "legendFormat": "实际使用/实际推荐占比 {{container}}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "实际使用量 {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "容器资源推荐情况【$Container】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "实际内存使用量",
     "type": "timeseries",
     "description": "sum (container_memory_working_set_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{container=~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container,pod)",
       "legendFormat": "{{container}} {{pod}}"
      }
     ]
    },
    {
     "title": "内存配置量",
     "type": "timeseries",
     "description": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)",
       "legendFormat": "{{container}} {{pod}}"
      }
     ]
    },
    {
     "title": "工作负载 CPU推荐情况",
     "type": "timeseries",
     "description": "sum(crane_analysis_resource_recommendation{resource=\"memory\",namespace=\"$NameSpace\",owner_kind=\"$WorkloadType\",owner_name=\"$Workload\",container=~\"$Container\"}) by (owner_name,namespace,resource,container)",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(crane_analysis_resource_recommendation{resource=\"cpu\",namespace=~\"$NameSpace\",owner_kind=\"$WorkloadType\",owner_name=~\"$Workload\",container=~\"$Container\"}) by (owner_name,namespace,resource,container)",
       "legendFormat": "CPU 推荐量 {{container}}"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container)",
       "legendFormat": "CPU 使用量 {{container}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container)",
       "legendFormat": "CPU 申请量 {{container}}"
      }
     ]
    },
    {
     "title": "工作负载 内存推荐量",
     "type": "timeseries",
     "description": "sum(crane_analysis_resource_recommendation{resource=\"memory\",namespace=\"$NameSpace\",owner_kind=\"$WorkloadType\",owner_name=\"$Workload\",container=~\"$Container\"}) by (owner_name,namespace,resource,container)",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(crane_analysis_resource_recommendation{resource=\"memory\",namespace=~\"$NameSpace\",owner_kind=\"$WorkloadType\",owner_name=~\"$Workload\",container=~\"$Container\"}) by (owner_name,namespace,resource,container)",
       "legendFormat": "{{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "容器资源配置浪费情况",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "内存浪费率（申请/实际）展板排行榜【$Workload】【$Container】",
     "type": "timeseries",
     "description": "值越大代表浪费的越多 【 request  >> usage 】\n值越小代表过度利用的越多【 request  << usage 】\n\n本着Request值与实际使用值越接近的原则，Request值使用不足95% 认为存在浪费的情况\n\n计算公式说明：\n1. (节点request - wss * 1.05)/节点request\n2. 计算值为负数则代表存在过度利用情况，实际使用大于实际申请\n3. 计算值为正数则代表存在浪费情况，实际申请request未充分利用，大于实际使用",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "(sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",container=~\"$Container\",pod=~\"$Pod\",node=~\"^$Node$\"}) by (container) - sum (container_memory_working_set_bytes{container !=\"\",container!=\"POD\",container=~\"$Container\",pod=~\"$Pod\",node=~\"^$Node$\"})  by (container) * 1.05) / sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (container)",
       "legendFormat": "资源浪费率  {{container}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",container=~\"$Container\",pod=~\"$Pod\",node=~\"^$Node$\"})by (container)",
       "legendFormat": "已分配资源 {{container}}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{container !=\"\",container=~\"$Container\",pod=~\"$Pod\",container!=\"POD\",node=~\"^$Node$\"}) by (container)",
       "legendFormat": "已使用资源 {{container}}"
      },
      {
       "expr": "sum(kube_node_status_allocatable{resource=\"memory\", container=~\"$Container\",pod=~\"$Pod\",unit=\"byte\", node=~\"^$Node$\"})by (container)",
       "legendFormat": "可分配资源 {{container}}"
      }
     ]
    },
    {
     "title": "CPU 浪费率（申请/实际）展板排行榜【$Workload】【$Container】",
     "type": "timeseries",
     "description": "值越大代表浪费的越多 【 request  >> usage 】\n值越小代表过度利用的越多【 request  << usage 】\n\n本着Request值与实际使用值越接近的原则，Request值使用不足95% 认为存在浪费的情况\n\n计算公式说明：\n1. (节点request - wss * 1.05)/节点request\n2. 计算值为负数则代表存在过度利用情况，实际使用大于实际申请\n3. 计算值为正数则代表存在浪费情况，实际申请request未充分利用，大于实际使用",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 6 },
     "targets": [
      {
       "expr": "(sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace) - sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace) * 1.05) / sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)",
       "legendFormat": "资源浪费率  {{container}}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)",
       "legendFormat": "已分配资源 {{container}}"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace)",
       "legendFormat": "已使用资源 {{container}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod资源使用明细",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "$Node：Pod资源明细(可关联节点)",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace) / (sum(container_spec_cpu_quota{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}/100000) by (container, pod,node,namespace)) * 100"
      },
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace)",
       "legendFormat": "CPU核数使用"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace) * 100",
       "legendFormat": "wss%"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
       "legendFormat": "wss"
      },
      {
       "expr": "sum (container_memory_rss{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace) * 100",
       "legendFormat": "rss%"
      },
      {
       "expr": "sum (container_memory_rss{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
       "legendFormat": "rss"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "sum(container_fs_usage_bytes{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
      },
      {
       "expr": "kube_pod_container_status_restarts_total{pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"} * on (pod) group_left(node) kube_pod_info{pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}"
      }
     ]
    }
   ]
  }
 ]
}