{
 "title": "Costs by Dimension",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Discount", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "Namespace consumed resource usage costs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "last--hours-total-costs-by-namespace{${__from:date:YYYY-MM-DD-hh}->${__to:date:YYYY-MM-DD-hh}}",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum_over_time(namespace:container_cpu_usage_costs_hourly:sum_rate{}[$__range]) + \n    sum_over_time(namespace:container_memory_usage_costs_hourly:sum_rate{}[$__range])\n) by (namespace) * ($Discount/100.0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Last-7day-costs-by-namespace",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum_over_time(namespace:container_cpu_usage_costs_hourly:sum_rate{}[7d]) + \n    sum_over_time(namespace:container_memory_usage_costs_hourly:sum_rate{}[7d])\n) by (namespace) * ($Discount/100.0)"
    }
   ]
  },
  {
   "title": "Last-30day-costs-by-namespace",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum_over_time(namespace:container_cpu_usage_costs_hourly:sum_rate{}[30d]) + \n    sum_over_time(namespace:container_memory_usage_costs_hourly:sum_rate{}[30d])\n) by (namespace) * ($Discount/100.0)"
    }
   ]
  },
  {
   "title": "Namespace-hourly-resource-usage-cost-trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Total Resource Usage Hourly Cost",
   "type": "graph",
   "description": "Total Resource Usage Hourly Cost by Namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "currencyJPY" }
   ],
   "targets": [
    {
     "expr": "sum (\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n  \n+\n\nsum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n  avg(avg_over_time(node_ram_hourly_cost[1h])) by (node)\n) by (namespace) * ($Discount/100.0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Ram Resource Usage Houly Cost",
   "type": "graph",
   "description": "Ram Resource Usage Houly Cost by Namespace",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  sum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n  avg(avg_over_time(node_ram_hourly_cost[1h])) by (node)\n) by (namespace) * ($Discount/100.0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Resource Usage Hourly Cost",
   "type": "graph",
   "description": "CPU Resource Usage Hourly cost by namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "currencyJPY" }
   ],
   "targets": [
    {
     "expr": "sum(\n\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n\n\n  ) by (namespace) * ($Discount/100.0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Estimated Namespace Resource Usage Monthly Cost",
   "type": "piechart",
   "description": "Estimated Namespace Monthly Cost according latest hourly cost",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n\n+\n\nsum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n  avg(avg_over_time(node_ram_hourly_cost[1h])) by (node)\n) by (namespace)  * 730 * ($Discount/100.0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "TopK Container Total Usage Costs{${__from:date:YYYY-MM-DD-hh}->${__to:date:YYYY-MM-DD-hh}}",
   "type": "table",
   "description": "Top K container costs of latest hour",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "topk(20, sum(\n    sum_over_time(namespace:container_cpu_usage_costs_hourly:sum_rate{}[$__range]) + \n    sum_over_time(namespace:container_memory_usage_costs_hourly:sum_rate{}[$__range])\n) by (container,namespace,pod) * ($Discount/100.0)\n) "
    }
   ]
  },
  {
   "title": "TopK Container Total Usage Costs Latest 1 Hour",
   "type": "table",
   "description": "Top K container costs of latest hour",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(20, sum (\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n\n+\n\nsum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n  avg(avg_over_time(node_ram_hourly_cost[1h])) by (node)\n) by (container, pod, node, namespace)) * ($Discount/100.0)"
    }
   ]
  },
  {
   "title": "TopK Container Cpu Usage Costs Latest 1 Hour",
   "type": "table",
   "description": "Top K container cpu usage costs of latest hour",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "topk(20, sum (\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n) by (container, pod, node, namespace) * ($Discount/100.0) )"
    }
   ]
  },
  {
   "title": "TopK Container Mem Usage Costs Latest 1 Hour",
   "type": "table",
   "description": "Top K container costs of latest hour",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "topk(20, sum (\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n\n+\n\nsum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n  avg(avg_over_time(node_ram_hourly_cost[1h])) by (node)\n) by (container, pod, node, namespace) * ($Discount/100.0))"
    }
   ]
  }
 ]
}