{
 "title": "Namespace Costs",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{},namespace)"
    }
   },
   { "name": "Discount", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "CPU Hourly Costs Over Time By Namespace ${namespace}",
   "type": "timeseries",
   "description": "cpu requests and usage costs given namespace ${namespace}",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "expr": "sum(\n  sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"$namespace\"}) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n      avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n      ) by (node)\n   ) by (node)\n) * ($Discount/100.)",
     "legendFormat": "requests-costs"
    },
    {
     "expr": "sum(\n  sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\",namespace=\"$namespace\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node) \n  ) by (node)\n) * ($Discount/100.)",
     "legendFormat": "usage-costs"
    }
   ]
  },
  {
   "title": "RAM Hourly Costs Over Time By Namespace ${namespace}",
   "type": "timeseries",
   "description": "ram requests and usage costs given namespace ${namespace}",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "expr": "sum(\n  sum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\",namespace=\"$namespace\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node)\n) * ($Discount/100.)",
     "legendFormat": "usage-costs"
    },
    {
     "expr": "sum(\n  sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace=\"$namespace\"} / 1024./ 1024. / 1024.) by (container, pod, node, namespace) * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * ($Discount/100.)",
     "legendFormat": "requests-costs"
    }
   ]
  },
  {
   "title": "Hourly Costs Over Time By Namespace ${namespace}",
   "type": "timeseries",
   "description": "requests and usage costs given namespace ${namespace}",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "expr": "sum(\n  sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"$namespace\"}) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n      avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n      ) by (node)\n   ) by (node)\n) * ($Discount/100.)\n\n+\n\nsum(\n  sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace=\"$namespace\"} / 1024./ 1024. / 1024.) by (container, pod, node, namespace) * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * ($Discount/100.)",
     "legendFormat": "requests-costs"
    },
    {
     "expr": "sum(\n  sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\",namespace=\"$namespace\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node) \n  ) by (node)\n) * ($Discount/100.)\n+\nsum(\n  sum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\",namespace=\"$namespace\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * ($Discount/100.)",
     "legendFormat": "usage-costs"
    }
   ]
  },
  {
   "title": "namespace(${namespace}) total usage costs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum_over_time(namespace:container_cpu_usage_costs_hourly:sum_rate{namespace=\"$namespace\"}[$__range]) + \n    sum_over_time(namespace:container_memory_usage_costs_hourly:sum_rate{namespace=\"$namespace\"}[$__range])\n) by (namespace) * ($Discount/100.0)"
    }
   ]
  }
 ]
}