{
 "title": "Node Analysis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_uname_info, nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=\"$node\"}, instance)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Container Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by(pod) (label_replace(container_memory_usage_bytes{kubernetes_io_hostname=\"$node\", pod!=\"\"}, \"node\", \"$1\", \"kubernetes_io_hostname\",  \"(.*)\")/on(node) group_left() node_memory_MemTotal_bytes{node=\"$node\"})"
    }
   ]
  },
  {
   "title": "Container CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\", node=~\"$node\",pod!=\"\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Node Memory Requests Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\",node!=\"miner-virtual-kubelet\",pod!=\"\"})/sum by (node) (kube_node_status_capacity{resource=\"memory\", unit=\"byte\",node!=\"miner-virtual-kubelet\"})"
    }
   ]
  },
  {
   "title": "Node Memory Usage Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (label_replace(container_memory_usage_bytes{pod!=\"\"}, \"node\", \"$1\", \"kubernetes_io_hostname\",  \"(.*)\"))/sum by (node) (kube_node_status_capacity{resource=\"memory\", unit=\"byte\",node!=\"miner-virtual-kubelet\"})"
    }
   ]
  },
  {
   "title": "Node Cpu Usage Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (label_replace(irate(container_cpu_usage_seconds_total{pod!=\"\"}[5m]), \"node\", \"$1\", \"kubernetes_io_hostname\",  \"(.*)\"))/sum by (node) ({resource=\"cpu\", unit=\"core\",node!=\"miner-virtual-kubelet\"})"
    }
   ]
  },
  {
   "title": "Node Cpu Requests Percentage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\",node!=\"miner-virtual-kubelet\",pod!=\"\"})/sum by (node) ({resource=\"cpu\", unit=\"core\",node!=\"miner-virtual-kubelet\"})"
    }
   ]
  },
  {
   "title": "Node Tainted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node)  (kube_node_spec_taint{effect=\"PreferNoSchedule\",key=\"interference.crane.io\"}==1)"
    }
   ]
  }
 ]
}