{
 "title": "Workload Utilization and Recommendation",
 "description": "Workload Utilization and Recommendation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{}, nodename)"
    }
   },
   { "name": "Namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "WorkloadType",
    "label": "WorkloadType",
    "query": {
     "query": "label_values(crane_analysis_resource_recommendation{namespace=~\"$Namespace\"},owner_kind)"
    }
   },
   {
    "name": "Workload",
    "label": "Workload",
    "query": {
     "query": "label_values(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"$WorkloadType\"},owner_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Workload Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workload CPU",
   "type": "timeseries",
   "description": "Dashboard for all recommended workloads. Only include pods that are recommended by crane.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"^$Workload-.*$\",container!=\"POD\",namespace=~\"$Namespace\",container!=\"\"}[3m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"cpu\",owner_name=~\"$Workload\"})",
     "legendFormat": "recommend"
    },
    {
     "expr": "SUM(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Workload Memory(GB)",
   "type": "timeseries",
   "description": "Dashboard for all recommended workloads. Only include pods that are recommended by crane.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"^$Workload-.*$\",namespace=~\"$Namespace\",container!=\"\"})/1024/1024/1024",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"byte\",resource=\"memory\",pod=~\"^$Workload-.*$\"})/1024/1024/1024",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"memory\",owner_name=~\"$Workload\"})/1024/1024/1024",
     "legendFormat": "recommend"
    },
    {
     "expr": "SUM(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)  / 1024 / 1024 / 1024 )",
     "legendFormat": "capacity"
    }
   ]
  },
  { "title": "Workload Slacks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Workload Spec CPU Slack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n- \nsum by (workload) (label_replace(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"Deployment\",resource=\"cpu\",owner_name=~\"$Workload\"}, \"workload\", \"$1\", \"owner_name\", \"(.*)\"))"
    }
   ]
  },
  {
   "title": "Workload Spec Memory Slack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(avg by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"byte\",resource=\"memory\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n- \nsum by (workload) (label_replace(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"Deployment\",resource=\"memory\",owner_name=~\"$Workload\"}, \"workload\", \"$1\", \"owner_name\", \"(.*)\")))/1024/1024/1024"
    }
   ]
  },
  {
   "title": "Workload Total CPU Slack",
   "type": "timeseries",
   "description": "Workload pods total cpu slack",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n- \n(sum by (workload) (label_replace(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"Deployment\",resource=\"cpu\",owner_name=~\"$Workload\"}, \"workload\", \"$1\", \"owner_name\", \"(.*)\"))\n*\ncount by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n)"
    }
   ]
  },
  {
   "title": "Workload Total Memory Slack",
   "type": "timeseries",
   "description": "Workload total memory slack for all pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(sum by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"byte\",resource=\"memory\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n- \n(sum by (workload) (label_replace(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"Deployment\",resource=\"memory\",owner_name=~\"$Workload\"}, \"workload\", \"$1\", \"owner_name\", \"(.*)\"))\n*\ncount by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"byte\",resource=\"memory\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n)\n)/1024/1024/1024"
    }
   ]
  }
 ]
}