{
 "title": "Cluster Cost & Utilization Overview",
 "description": "A dashboard to help manage Kubernetes cluster costs and resources",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Discount", "query": "100" }
  ]
 },
 "panels": [
  { "title": "Cost Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Estimated Monthly Cluster Resource Costs",
   "type": "bargauge",
   "description": "Monthly estimated costs according to latest 1 hour resource usage, Note, if you use virtual kubelet or EKS Pod, we do not compute the virtual node costs.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    avg(\n        avg_over_time(node_total_hourly_cost[1h])\n        * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n    )\n     \nby (node)) * 730 * ($Discount/100.0)"
    },
    {
     "expr": "sum(\n  sum(\n    sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}) by (container, pod, node, namespace) \n    * on (node) group_left() \n    avg(\n      avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n    ) by (node)\n    \n)\n\n+\n\nsum(\n  sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"} / 1024./ 1024. / 1024.) by (container, pod, node, namespace) \n  * on (node) group_left() \n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n  ) by (node) \n  \n)\n) * 730 * ($Discount/100.0)"
    },
    {
     "expr": "sum (\n  sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node) \n  ) by (node)\n\n+\n\n  sum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * 730 * ($Discount/100.)"
    },
    {
     "expr": "sum(\n  sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n      avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n      ) by (node)\n  ) by (node)\n) * 730 * ($Discount/100.)"
    },
    {
     "expr": "sum(\n  sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"} / 1024./ 1024. / 1024.) by (container, pod, node, namespace) * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * 730 * ($Discount/100.)"
    },
    {
     "expr": "sum(\n  sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(\n    avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * 730 * ($Discount/100.)"
    },
    {
     "expr": "sum(\n  sum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n    avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * 730 * ($Discount/100.)"
    }
   ]
  },
  {
   "title": "Node Resource Cost & Utilization",
   "type": "table",
   "description": "This table shows the comparison of application CPU usage vs the capacity of the node (measured over last 60 minutes)",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"} \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node) \n\n/\n\nsum(\n  kube_node_status_capacity{resource=\"cpu\", unit=\"core\"} \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node) \n\n* 100"
    },
    {
     "expr": "sum(\n  label_replace(irate(container_cpu_usage_seconds_total{container!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"^[^:]+\") \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node)\n/\nsum(\n  kube_node_status_capacity{resource=\"cpu\", unit=\"core\"} \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n) by (node) \n\n* 100"
    },
    {
     "expr": "avg(\n  avg_over_time(node_cpu_hourly_cost[1h]) \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node)  * ($Discount/100.)"
    },
    {
     "expr": "sum(\n\n  sum(\n    label_replace(irate(container_cpu_usage_seconds_total{container!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(^[^:]+)\")  \n     * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n  ) by (container, pod, node, namespace) \n\n  * on (node) group_left() \n \n  avg(\n    avg_over_time(node_cpu_hourly_cost[1h])  \n    * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n  ) by (node) \n\n) by (node)  * ($Discount/100.)"
    },
    {
     "expr": "sum(\n  kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"}  \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n) by (node) * 100\n\n/ \n\nsum(\n  kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}  \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node)"
    },
    {
     "expr": "sum(\n  label_replace(container_memory_usage_bytes{container!=\"\"}, \"node\", \"$1\", \"instance\",\"(^[^:]+)\")  \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node) * 100\n\n/\nsum(\n  kube_node_status_capacity{resource=\"memory\", unit=\"byte\"} \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n) by (node)"
    },
    {
     "expr": "avg(\n  avg_over_time(node_ram_hourly_cost[1h])) by (node) \n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n) by (node)  * ($Discount/100.)"
    },
    {
     "expr": "sum(\n\n  sum(\n    label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(^[^:]+)\") \n    * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)\n  ) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 \n\n  * on (node) group_left()\n\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) \n    * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n  ) by (node)\n  \n) by (node)  * ($Discount/100.)\n"
    },
    {
     "expr": "avg(\n  avg_over_time(node_total_hourly_cost[1h])\n  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) \n) by (node) * ($Discount/100.)"
    }
   ]
  },
  {
   "title": "Cluster Utilization Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "description": "Current CPU utilization from applications usage vs allocatable CPU",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"\"}[5m]), \"node\", \"$1\", \"instance\",  \"(^[^:]+)\")  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))\n\n/\n\nsum(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"} * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)) \n\n* 100"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "gauge",
   "description": "Current CPU reservation requests from applications vs allocatable CPU",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"} * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) ) \n/ \nsum(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"} * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) )\n* 100"
    }
   ]
  },
  {
   "title": "RAM Utilization",
   "type": "gauge",
   "description": "Current RAM use vs RAM available",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(label_replace(container_memory_working_set_bytes{container!=\"\"}, \"node\", \"$1\", \"instance\",  \"(^[^:]+)\")  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))\n\n/\n\nsum(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"} * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) ) \n* 100"
    }
   ]
  },
  {
   "title": "RAM Requests",
   "type": "gauge",
   "description": "Current RAM requests vs RAM available",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) )\n /\n sum(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node) )\n) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "SUM(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))",
     "legendFormat": "capacity"
    },
    {
     "expr": "SUM(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"\"}[5m]), \"node\", \"$1\", \"instance\",  \"(^[^:]+)\")  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Cluster Memory (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "SUM(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)  / 1024 / 1024 / 1024 )",
     "legendFormat": "capacity"
    },
    {
     "expr": "SUM(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace!=\"\"} * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)/ 1024 / 1024 / 1024)",
     "legendFormat": "requests"
    },
    {
     "expr": "SUM(label_replace(container_memory_working_set_bytes{id=\"/\"}, \"node\", \"$1\", \"instance\",  \"(^[^:]+)\")  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)) / 1024 / 1024 / 1024",
     "legendFormat": "usage"
    }
   ]
  },
  {
   "title": "Node Utilization Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (label_replace(irate(container_cpu_usage_seconds_total{container!=\"\"}[5m]), \"node\", \"$1\", \"instance\",  \"(^[^:]+)\"))/sum by (node) (kube_node_status_capacity{resource=\"cpu\", unit=\"core\",node!~\"eklet\"})",
     "legendFormat": "cpu utilization"
    }
   ]
  },
  {
   "title": "Node Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (label_replace(container_memory_working_set_bytes{container!=\"\"}, \"node\", \"$1\", \"instance\",  \"(^[^:]+)\"))/sum by (node) (kube_node_status_capacity{resource=\"memory\", unit=\"byte\",node!~\"eklet\"})",
     "legendFormat": "cpu utilization"
    }
   ]
  }
 ]
}
{
 "title": "Costs by Dimension",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Discount", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "Namespace consumed resource usage costs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "last--hours-total-costs-by-namespace{${__from:date:YYYY-MM-DD-hh}->${__to:date:YYYY-MM-DD-hh}}",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum_over_time(namespace:container_cpu_usage_costs_hourly:sum_rate{}[$__range]) + \n    sum_over_time(namespace:container_memory_usage_costs_hourly:sum_rate{}[$__range])\n) by (namespace) * ($Discount/100.0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Last-7day-costs-by-namespace",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum_over_time(namespace:container_cpu_usage_costs_hourly:sum_rate{}[7d]) + \n    sum_over_time(namespace:container_memory_usage_costs_hourly:sum_rate{}[7d])\n) by (namespace) * ($Discount/100.0)"
    }
   ]
  },
  {
   "title": "Last-30day-costs-by-namespace",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum_over_time(namespace:container_cpu_usage_costs_hourly:sum_rate{}[30d]) + \n    sum_over_time(namespace:container_memory_usage_costs_hourly:sum_rate{}[30d])\n) by (namespace) * ($Discount/100.0)"
    }
   ]
  },
  {
   "title": "Namespace-hourly-resource-usage-cost-trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "Total Resource Usage Hourly Cost",
   "type": "graph",
   "description": "Total Resource Usage Hourly Cost by Namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "currencyJPY" }
   ],
   "targets": [
    {
     "expr": "sum (\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n  \n+\n\nsum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n  avg(avg_over_time(node_ram_hourly_cost[1h])) by (node)\n) by (namespace) * ($Discount/100.0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Ram Resource Usage Houly Cost",
   "type": "graph",
   "description": "Ram Resource Usage Houly Cost by Namespace",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  sum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n  avg(avg_over_time(node_ram_hourly_cost[1h])) by (node)\n) by (namespace) * ($Discount/100.0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Resource Usage Hourly Cost",
   "type": "graph",
   "description": "CPU Resource Usage Hourly cost by namespace",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "currencyJPY" }
   ],
   "targets": [
    {
     "expr": "sum(\n\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n\n\n  ) by (namespace) * ($Discount/100.0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Estimated Namespace Resource Usage Monthly Cost",
   "type": "piechart",
   "description": "Estimated Namespace Monthly Cost according latest hourly cost",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"(.*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n\n+\n\nsum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n  avg(avg_over_time(node_ram_hourly_cost[1h])) by (node)\n) by (namespace)  * 730 * ($Discount/100.0)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "TopK Container Total Usage Costs{${__from:date:YYYY-MM-DD-hh}->${__to:date:YYYY-MM-DD-hh}}",
   "type": "table",
   "description": "Top K container costs of latest hour",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "topk(20, sum(\n    sum_over_time(namespace:container_cpu_usage_costs_hourly:sum_rate{}[$__range]) + \n    sum_over_time(namespace:container_memory_usage_costs_hourly:sum_rate{}[$__range])\n) by (container,namespace,pod) * ($Discount/100.0)\n) "
    }
   ]
  },
  {
   "title": "TopK Container Total Usage Costs Latest 1 Hour",
   "type": "table",
   "description": "Top K container costs of latest hour",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "topk(20, sum (\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n\n+\n\nsum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n  avg(avg_over_time(node_ram_hourly_cost[1h])) by (node)\n) by (container, pod, node, namespace)) * ($Discount/100.0)"
    }
   ]
  },
  {
   "title": "TopK Container Cpu Usage Costs Latest 1 Hour",
   "type": "table",
   "description": "Top K container cpu usage costs of latest hour",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "topk(20, sum (\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n) by (container, pod, node, namespace) * ($Discount/100.0) )"
    }
   ]
  },
  {
   "title": "TopK Container Mem Usage Costs Latest 1 Hour",
   "type": "table",
   "description": "Top K container costs of latest hour",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "topk(20, sum (\nsum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) * on (node) group_left()\n  avg(avg_over_time(node_cpu_hourly_cost[1h])) by (node)\n\n+\n\nsum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 * on (node) group_left()\n  avg(avg_over_time(node_ram_hourly_cost[1h])) by (node)\n) by (container, pod, node, namespace) * ($Discount/100.0))"
    }
   ]
  }
 ]
}
{
 "title": "Namespace Costs",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_namespace_created{},namespace)"
    }
   },
   { "name": "Discount", "query": "100" }
  ]
 },
 "panels": [
  {
   "title": "CPU Hourly Costs Over Time By Namespace ${namespace}",
   "type": "timeseries",
   "description": "cpu requests and usage costs given namespace ${namespace}",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "expr": "sum(\n  sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"$namespace\"}) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n      avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n      ) by (node)\n   ) by (node)\n) * ($Discount/100.)",
     "legendFormat": "requests-costs"
    },
    {
     "expr": "sum(\n  sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\",namespace=\"$namespace\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node) \n  ) by (node)\n) * ($Discount/100.)",
     "legendFormat": "usage-costs"
    }
   ]
  },
  {
   "title": "RAM Hourly Costs Over Time By Namespace ${namespace}",
   "type": "timeseries",
   "description": "ram requests and usage costs given namespace ${namespace}",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "expr": "sum(\n  sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace=\"$namespace\"} / 1024./ 1024. / 1024.) by (container, pod, node, namespace) * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * ($Discount/100.)",
     "legendFormat": "requests-costs"
    },
    {
     "expr": "sum(\n  sum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\",namespace=\"$namespace\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node)\n) * ($Discount/100.)",
     "legendFormat": "usage-costs"
    }
   ]
  },
  {
   "title": "Hourly Costs Over Time By Namespace ${namespace}",
   "type": "timeseries",
   "description": "requests and usage costs given namespace ${namespace}",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "targets": [
    {
     "expr": "sum(\n  sum(kube_pod_container_resource_requests{resource=\"cpu\", unit=\"core\", namespace=\"$namespace\"}) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n      avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n      ) by (node)\n   ) by (node)\n) * ($Discount/100.)\n\n+\n\nsum(\n  sum(kube_pod_container_resource_requests{resource=\"memory\", unit=\"byte\", namespace=\"$namespace\"} / 1024./ 1024. / 1024.) by (container, pod, node, namespace) * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * ($Discount/100.)",
     "legendFormat": "requests-costs"
    },
    {
     "expr": "sum(\n  sum(label_replace(irate(container_cpu_usage_seconds_total{container!=\"POD\", container!=\"\",image!=\"\",namespace=\"$namespace\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_cpu_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\",label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node) \n  ) by (node)\n) * ($Discount/100.)\n+\nsum(\n  sum(label_replace(avg_over_time(container_memory_working_set_bytes{container!=\"POD\",container!=\"\",image!=\"\",namespace=\"$namespace\"}[1h]), \"node\", \"$1\", \"instance\",  \"([0-9.]*)\")) by (container, pod, node, namespace) / 1024.0 / 1024.0 / 1024.0 \n  * on (node) group_left()\n  avg(\n    avg_over_time(node_ram_hourly_cost[1h]) * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!~\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}\n    ) by (node)\n  ) by (node) \n) * ($Discount/100.)",
     "legendFormat": "usage-costs"
    }
   ]
  },
  {
   "title": "namespace(${namespace}) total usage costs",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyJPY" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    sum_over_time(namespace:container_cpu_usage_costs_hourly:sum_rate{namespace=\"$namespace\"}[$__range]) + \n    sum_over_time(namespace:container_memory_usage_costs_hourly:sum_rate{namespace=\"$namespace\"}[$__range])\n) by (namespace) * ($Discount/100.0)"
    }
   ]
  }
 ]
}
{
 "title": "Workload Insight",
 "description": "Workload Insight",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "WorkloadType",
    "label": "WorkloadType",
    "query": {
     "query": "label_values(crane_analysis_resource_recommendation{namespace=~\"$Namespace\"},owner_kind)"
    }
   },
   {
    "name": "Workload",
    "label": "Workload",
    "query": {
     "query": "label_values(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"$WorkloadType\"},owner_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Workload Pods Insight - CPU",
   "type": "timeseries",
   "description": "Workload optimize model dashboard, calculate all pods metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"^$Workload-.*$\",container!=\"POD\",namespace=\"$Namespace\",container!=\"\"}[3m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"cpu\",owner_name=~\"$Workload\"}) *\ncount(kube_pod_info{namespace=\"$Namespace\",pod=~\"^crane-scheduler-.*$\",})\n",
     "legendFormat": "recommend"
    }
   ]
  },
  {
   "title": "Workload Pods Insight - CPU",
   "type": "timeseries",
   "description": "Workload optimize model dashboard, calculate all pods metric",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"^$Workload-.*$\",container!=\"POD\",namespace=\"$Namespace\",container!=\"\"}[3m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"cpu\",owner_name=~\"$Workload\"}) *\ncount(kube_pod_info{namespace=\"$Namespace\",pod=~\"^crane-scheduler-.*$\",})\n",
     "legendFormat": "recommend"
    }
   ]
  },
  {
   "title": "Workload Spec Insight - CPU",
   "type": "timeseries",
   "description": "Workload insight for CPU, Spec level",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(irate(container_cpu_usage_seconds_total{pod=~\"^$Workload-.*$\",container!=\"POD\",namespace=\"$Namespace\",container!=\"\"}[3m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"cpu\",owner_name=~\"$Workload\"})\n",
     "legendFormat": "recommend"
    }
   ]
  },
  {
   "title": "Workload Spec Insight - Memory(GB)",
   "type": "timeseries",
   "description": "Workload Insight, Spec level.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "avg(container_memory_working_set_bytes{pod=~\"^$Workload-.*$\",namespace=\"$Namespace\",container!=\"\"})/1024/1024/1024",
     "legendFormat": "usage"
    },
    {
     "expr": "avg(kube_pod_container_resource_requests{namespace=\"$Namespace\",unit=\"byte\",resource=\"memory\",pod=~\"^$Workload-.*$\"})/1024/1024/1024",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"memory\",owner_name=~\"$Workload\"})\n/1024/1024/1024 ",
     "legendFormat": "recommend"
    }
   ]
  }
 ]
}
{
 "title": "Workload Utilization and Recommendation",
 "description": "Workload Utilization and Recommendation",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info{}, nodename)"
    }
   },
   { "name": "Namespace", "label": "Namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "WorkloadType",
    "label": "WorkloadType",
    "query": {
     "query": "label_values(crane_analysis_resource_recommendation{namespace=~\"$Namespace\"},owner_kind)"
    }
   },
   {
    "name": "Workload",
    "label": "Workload",
    "query": {
     "query": "label_values(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"$WorkloadType\"},owner_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Workload Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Workload CPU",
   "type": "timeseries",
   "description": "Dashboard for all recommended workloads. Only include pods that are recommended by crane.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{pod=~\"^$Workload-.*$\",container!=\"POD\",namespace=~\"$Namespace\",container!=\"\"}[3m]))",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"})",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"cpu\",owner_name=~\"$Workload\"})",
     "legendFormat": "recommend"
    },
    {
     "expr": "SUM(kube_node_status_capacity{resource=\"cpu\", unit=\"core\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node))",
     "legendFormat": "capacity"
    }
   ]
  },
  {
   "title": "Workload Memory(GB)",
   "type": "timeseries",
   "description": "Dashboard for all recommended workloads. Only include pods that are recommended by crane.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"^$Workload-.*$\",namespace=~\"$Namespace\",container!=\"\"})/1024/1024/1024",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"byte\",resource=\"memory\",pod=~\"^$Workload-.*$\"})/1024/1024/1024",
     "legendFormat": "request"
    },
    {
     "expr": "sum(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"$WorkloadType\",resource=\"memory\",owner_name=~\"$Workload\"})/1024/1024/1024",
     "legendFormat": "recommend"
    },
    {
     "expr": "SUM(kube_node_status_capacity{resource=\"memory\", unit=\"byte\"}  * on (node) group_left() max(kube_node_labels{label_beta_kubernetes_io_instance_type!=\"eklet\", label_node_kubernetes_io_instance_type!~\"eklet\"}) by (node)  / 1024 / 1024 / 1024 )",
     "legendFormat": "capacity"
    }
   ]
  },
  { "title": "Workload Slacks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Workload Spec CPU Slack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n- \nsum by (workload) (label_replace(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"Deployment\",resource=\"cpu\",owner_name=~\"$Workload\"}, \"workload\", \"$1\", \"owner_name\", \"(.*)\"))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workload Spec Memory Slack",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "(avg by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"byte\",resource=\"memory\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n- \nsum by (workload) (label_replace(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"Deployment\",resource=\"memory\",owner_name=~\"$Workload\"}, \"workload\", \"$1\", \"owner_name\", \"(.*)\")))/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workload Total CPU Slack",
   "type": "timeseries",
   "description": "Workload pods total cpu slack",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n- \n(sum by (workload) (label_replace(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"Deployment\",resource=\"cpu\",owner_name=~\"$Workload\"}, \"workload\", \"$1\", \"owner_name\", \"(.*)\"))\n*\ncount by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"core\",resource=\"cpu\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Workload Total Memory Slack",
   "type": "timeseries",
   "description": "Workload total memory slack for all pods",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "(sum by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"byte\",resource=\"memory\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n- \n(sum by (workload) (label_replace(crane_analysis_resource_recommendation{namespace=~\"$Namespace\",owner_kind=\"Deployment\",resource=\"memory\",owner_name=~\"$Workload\"}, \"workload\", \"$1\", \"owner_name\", \"(.*)\"))\n*\ncount by (workload) (label_replace(kube_pod_container_resource_requests{namespace=~\"$Namespace\",unit=\"byte\",resource=\"memory\",pod=~\"^$Workload-.*$\"}, \"workload\", \"$1\", \"pod\", \"(^$Workload)-.*$\"))\n)\n)/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}